import type { Content } from "./types";

export const en: Content = {
  meta: {
    siteName: "Nguyen Thi Thanh Tra — Digital Marketing",
    description:
      "Digital Marketing at GTG CRM (SaaS). 5+ years of multi-channel Digital Marketing — SEO, Performance Ads, Content, Brand Marketing and AI-native workflows across B2B and SaaS.",
  },
  nav: {
    about: "About",
    experience: "Experience",
    projects: "Highlights",
    skills: "Skills",
    education: "Education",
    contact: "Contact",
    cta: "Download CV",
  },
  hero: {
    eyebrow: "Open to opportunities",
    name: "Nguyen Thanh Tra",
    title: "Digital Marketing Specialist",
    location: "Go Vap · Ho Chi Minh City",
    intro:
      "Digital Marketing at GTG CRM (SaaS) — 5+ years building and operating integrated Digital Marketing strategies for B2B and SME businesses. Deep focus on SEO, Performance Marketing, Content Strategy, Brand Marketing, and AI-native workflows: leveraging Claude, ChatGPT, Gemini, Kling, and custom AI Agents to dramatically amplify marketing productivity.",
    primaryCta: "Download CV (PDF)",
    secondaryCta: "See achievements",
    availability: "Open to the right opportunity",
    portrait: "/images/avatar.jpg",
  },
  stats: [
    { value: "+60%", label: "Organic traffic growth" },
    { value: "+32%", label: "Email open rate lift" },
    { value: "20+", label: "Top-3 Google rankings" },
    { value: "200+", label: "Quality backlinks built" },
  ],
  about: {
    eyebrow: "Profile",
    headline: "Professional summary",
    paragraphs: [
      "Digital Marketer currently driving the marketing function at GTG CRM — a Vietnamese SaaS company offering CRM solutions across 4 customer segments (SME, Enterprise, Freelancer, Business). 5+ years of hands-on experience across 4 companies spanning multi-industry agency, import–distribution, B2B industrial equipment, and SaaS.",
      "My approach is data-driven and systematic. Every campaign ties to specific KPIs (organic traffic, CTR, CPC, conversion rate, open rate), is optimized on a regular cadence, and reported transparently to stakeholders. The end goal is always scalable, sustainable, and measurable growth.",
      "Core expertise: SEO, Performance Marketing, Content Strategy, Email Marketing Automation, Brand Identity, and Marketing Leadership. Heavy emphasis on integrating AI (Claude, ChatGPT, Gemini, Kling) into daily workflows and building custom AI Agents to amplify team productivity. Adapts quickly across industries — from long B2B decision cycles in industrial markets to product-led growth motions in SaaS.",
    ],
    cta: "Download CV PDF",
  },
  experience: {
    eyebrow: "Experience",
    headline: "My journey",
    items: [
      {
        role: "Digital Marketing",
        company: "GTG CRM Co., Ltd",
        period: "Jun 2025 — Present",
        location: "Ho Chi Minh City",
        industry: "SaaS · CRM Platform · Multi-segment",
        description:
          "End-to-end Digital Marketing for a SaaS CRM product serving 4 customer segments (SME, Enterprise, Freelancer, Business). Execute multi-channel marketing strategy, leverage AI to accelerate workflows, and make every decision data-driven — oriented toward scalable, sustainable growth.",
        keyMetrics: [
          { value: "↑ MoM", label: "Signup Growth Rate" },
          { value: "4", label: "Customer Segments" },
          { value: "AI-Native", label: "Marketing Workflow" },
        ],
        scope: [
          "Marketing Strategy (Multi-segment)",
          "Product Marketing (SaaS)",
          "Growth & Demand Generation",
          "Content Marketing & Programmatic SEO",
          "Performance Marketing",
          "Marketing Automation",
          "AI Integration & Agent Building",
          "Cross-functional Collaboration",
        ],
        achievements: [
          "Own the multi-segment Go-to-Market strategy for the SaaS CRM product — define ICP, positioning, and acquisition channels tailored per segment (SME, Enterprise, Freelancer, Business)",
          "Drive month-over-month signup growth — the core KPI measuring the effectiveness of the growth strategy",
          "Deep AI integration in daily workflows: Claude/ChatGPT/Gemini for content production & research, Kling AI for creative visuals, and custom AI Agents to automate the marketing pipeline — productivity gains multiple times higher than traditional methods",
          "Execute end-to-end SaaS B2B marketing funnel: SEO + content clusters, Paid Ads, Email Automation, and Lead Nurturing — with dedicated KPIs and dashboards per channel",
          "Experiment with new channels and formats aligned with 2025+ trends: short-form video, programmatic SEO, Generative Engine Optimization (GEO) for AI Search, and community-led growth",
          "Cross-functional collaboration with Product, Sales, and Customer Success — ensuring marketing message and growth strategy stay aligned across the entire customer journey",
        ],
        stack: ["HubSpot", "GA4", "GSC", "SEMrush", "Google Ads", "Meta Ads", "Marketing Automation", "Claude", "ChatGPT", "Gemini", "Kling AI", "Perplexity", "Notion"],
        logo: "/images/companies/gtg-crm.png",
      },
      {
        role: "Digital Marketing",
        company: "Thai Khuong Trading & Technology Co., Ltd",
        period: "Feb 2022 — Jun 2025",
        location: "Go Vap, HCMC",
        industry: "B2B · Industrial equipment importer",
        description:
          "Owning end-to-end Digital Marketing — from content strategy and SEO operations to paid ads, brand identity, exhibitions, and internal communications.",
        keyMetrics: [
          { value: "+40%", label: "Organic Traffic / 6mo" },
          { value: "+32%", label: "Email Open Rate" },
          { value: "3", label: "Persona content strategy" },
        ],
        scope: [
          "Brand Marketing & Campaign Planning",
          "Content & SEO",
          "Performance Marketing",
          "Email Marketing Automation",
          "Exhibition & Events",
          "Internal Communications",
        ],
        achievements: [
          "Achieved +40% organic traffic in 6 months by restructuring content funnels around End-user / Contractor / Distributor personas",
          "Led Email Marketing Automation on Getfly — drove a 32% increase in open rate and significantly improved response rates",
          "Designed long-term content roadmaps across Fanpage, TikTok & Website aligned to each customer segment",
          "Represented the company at industry exhibitions: Vietwater, Propak Vietnam, Waste & Recycling",
          "Lead writer of THONG TAN XA THAI KHUONG — internal communications channel connecting the entire company",
          "Manage all website content on WordPress; track user behavior via GA4 and Google Search Console",
        ],
        stack: ["SEMrush", "GSC", "GA4", "Getfly CRM", "WordPress", "Facebook Ads", "Google Ads", "Canva", "Figma"],
        logo: "/images/companies/thai-khuong.png",
      },
      {
        role: "Performance Marketing Executive",
        company: "Erabit Digital Marketing Co., Ltd",
        period: "Jun 2021 — Jan 2022",
        location: "Ho Chi Minh City",
        industry: "Marketing Agency · Multi-industry",
        description:
          "Executed dedicated SEO strategies for clients across multiple industries (Real Estate, Education, Services). Each project had its own content & SEO strategy aligned to specific search behavior.",
        keyMetrics: [
          { value: "+40%", label: "Organic Traffic / 6mo" },
          { value: "+25%", label: "Organic engagement" },
          { value: "Multi", label: "Industry portfolio" },
        ],
        scope: [
          "SEO Onpage & Offpage",
          "Social Media Strategy",
          "Website UX/UI Optimization",
          "Reporting & Analysis",
        ],
        achievements: [
          "Delivered +40% organic traffic growth in 6 months across multi-industry client projects",
          "Executed comprehensive SEO: keyword research, on-page optimization (title, meta, internal linking), off-page (backlinks, guest posts, satellite sites)",
          "Built a quality backlink system that improved domain authority and overall SEO strength",
          "Managed fanpages across industries — +25% engagement through behavior-matched content",
          "Contributed to UX/UI design and optimization on WordPress and Eraweb platforms",
          "Produced periodic analysis reports (weekly/monthly/quarterly) with concrete recommendations for sustainable SEO performance",
        ],
        stack: ["Ahrefs", "SEMrush", "Keywordtool.io", "GSC", "GA4", "WordPress", "Eraweb"],
        logo: "/images/companies/erabit.png",
      },
      {
        role: "Digital Marketing Executive",
        company: "NK&PP Dong Thai Co., Ltd",
        period: "Jul 2020 — Sep 2021",
        location: "Ho Chi Minh City",
        industry: "Import & Distribution",
        description:
          "Designed and executed full-funnel Digital Marketing: SEO, Performance Ads, online PR, and POSM/Sales Kit. Established the company's brand identity standards.",
        keyMetrics: [
          { value: "+60%", label: "Organic Traffic" },
          { value: "20+", label: "Top-3 Google rankings" },
          { value: "-20%", label: "CPC reduction" },
        ],
        scope: [
          "SEO Strategy & Execution",
          "Google & Facebook Ads",
          "Online PR & Media",
          "POSM / Sales Kit",
          "Brand Identity (CIP)",
        ],
        achievements: [
          "Produced 120+ SEO-optimized articles and built 200+ quality backlinks via guest posts, online media, and satellite sites",
          "Achieved Top 3 Google rankings for 20+ primary keywords with +60% organic traffic in 6 months",
          "Optimized Google Ads & Facebook Ads for branding and lead-gen — +25% conversions, -20% CPC after 3 months",
          "Partnered with online media for major PR campaigns — meaningful contribution to brand awareness",
          "Managed 2-3 fanpage posts per week with trend-driven content — +40% engagement vs. prior period",
          "Built and standardized the Brand Book, Logo Guidelines, and brand usage standards across all communication channels",
          "Delivered Sales Kit & POSM materials: Wobbler, Catalogue, Leaflet, Brochure, brand Profile",
        ],
        stack: ["SEMrush", "Ahrefs", "Google Ads", "Facebook Ads", "WordPress", "Online PR"],
        logo: "/images/companies/dong-thai.png",
      },
    ],
  },
  projects: {
    eyebrow: "Highlights",
    headline: "Results I'm proud of",
    description: "Concrete work I personally executed, with clear numbers.",
    items: [
      {
        slug: "thai-khuong-content",
        title: "Content Strategy & SEO for B2B Industrial",
        tagline: "Thai Khuong — Industrial equipment",
        description:
          "Persona-driven long-term content strategy across 3 segments (End-user, Contractor, Distributor), technical SEO writing, keyword management with SEMrush.",
        metrics: [
          { label: "Organic traffic", value: "+40%" },
          { label: "Within", value: "6 months" },
          { label: "Personas", value: "3 segments" },
        ],
        tags: ["B2B", "SEO", "Content"],
        cover: "/images/projects/thai-khuong-content.jpg",
      },
      {
        slug: "email-automation-getfly",
        title: "Email Marketing Automation funnel",
        tagline: "Thai Khuong — Getfly platform",
        description:
          "Automated email funnels for both new lead nurture and existing customer care, with subject line and content optimization per segment.",
        metrics: [
          { label: "Open rate", value: "+32%" },
          { label: "Response", value: "Up" },
          { label: "Platform", value: "Getfly" },
        ],
        tags: ["Email", "Automation", "B2B"],
        cover: "/images/projects/email-automation-getfly.jpg",
      },
      {
        slug: "dong-thai-seo",
        title: "Full-funnel SEO — Top 3 for 20+ keywords",
        tagline: "Dong Thai — Import & Distribution",
        description:
          "120+ SEO articles + 200+ quality backlinks via guest posts and satellite sites. On-page + off-page in 6 months.",
        metrics: [
          { label: "Organic traffic", value: "+60%" },
          { label: "Top-3 keywords", value: "20+" },
          { label: "SEO articles", value: "120+" },
        ],
        tags: ["SEO", "Backlinks", "On-page"],
        cover: "/images/projects/dong-thai-seo.jpg",
      },
      {
        slug: "dong-thai-performance",
        title: "Performance Ads — Lower CPC, higher conversion",
        tagline: "Dong Thai — Google & Facebook Ads",
        description:
          "Optimized Google & Facebook Ads for branding and lead-gen over 3 months, complemented by PR features for awareness.",
        metrics: [
          { label: "Conversions", value: "+25%" },
          { label: "CPC", value: "-20%" },
          { label: "Timeframe", value: "3 months" },
        ],
        tags: ["Performance", "Ads", "Lead-gen"],
        cover: "/images/projects/dong-thai-performance.jpg",
      },
    ],
    viewAll: "See all",
  },
  skills: {
    eyebrow: "Core competencies",
    headline: "Core competencies",
    description: "Self-assessed from real work across 4 companies.",
    items: [
      { name: "Strategy Planning", rating: 9 },
      { name: "AI Workflows & Agent Building", rating: 8.5 },
      { name: "Content Creator", rating: 8.5 },
      { name: "Digital Marketing & SEO", rating: 8 },
      { name: "Project & Campaign Management", rating: 8 },
      { name: "Communication & Collaboration", rating: 8 },
      { name: "Design & Visual Sense", rating: 7 },
    ],
    tools: [
      "Claude",
      "ChatGPT",
      "Gemini",
      "Kling AI",
      "Custom AI Agents",
      "HubSpot",
      "Getfly CRM",
      "SEMrush",
      "Ahrefs",
      "Google Search Console",
      "Google Analytics 4",
      "Keywordtool.io",
      "WordPress",
      "Eraweb",
      "Google Ads",
      "Facebook Ads Manager",
      "Canva",
      "Figma",
    ],
  },
  contact: {
    eyebrow: "Contact",
    headline: "Thanks for stopping by",
    description:
      "If my background matches what you're hiring for, I'd love to chat more.",
    cta: "Send email",
    downloadCv: "Download CV (PDF)",
    email: "nguyenthanhtratm@gmail.com",
    phone: "0849 357 729",
    website: "nguyenthanhtra.info",
    address: "Go Vap, Ho Chi Minh City",
  },
  footer: {
    tagline: "Multi-channel Digital Marketing — from a Quang Binh girl in Saigon.",
    sections: [
      {
        title: "Pages",
        links: [
          { label: "About", href: "#about" },
          { label: "Experience", href: "#experience" },
          { label: "Highlights", href: "#projects" },
          { label: "Skills", href: "#skills" },
          { label: "Education", href: "#education" },
          { label: "Contact", href: "#contact" },
        ],
      },
      {
        title: "Contact",
        links: [
          { label: "nguyenthanhtratm@gmail.com", href: "mailto:nguyenthanhtratm@gmail.com" },
          { label: "0849 357 729", href: "tel:+84849357729" },
          { label: "nguyenthanhtra.info", href: "https://nguyenthanhtra.info" },
        ],
      },
    ],
    social: [
      { label: "Email", href: "mailto:nguyenthanhtratm@gmail.com", icon: "mail" },
      { label: "Phone", href: "tel:+84849357729", icon: "phone" },
      { label: "Website", href: "https://nguyenthanhtra.info", icon: "globe" },
    ],
    copyright: "© 2026 Nguyen Thi Thanh Tra.",
  },
  education: {
    eyebrow: "Education",
    headline: "Background",
    items: [
      {
        school: "Industrial University of Ho Chi Minh City (IUH)",
        degree: "B.A. in E-Commerce",
        period: "Graduated 2022",
        detail: "GPA: 3.0/4.0",
      },
    ],
  },
};
