import type { Content } from "./types";

export const vi: Content = {
  meta: {
    siteName: "Nguyễn Thị Thanh Trà — Digital Marketing",
    description:
      "Digital Marketing tại GTG CRM (SaaS). 5+ năm kinh nghiệm Digital Marketing đa kênh — SEO, Performance Ads, Content, Brand Marketing và AI-native workflows cho B2B và SaaS.",
  },
  nav: {
    about: "Giới thiệu",
    experience: "Kinh nghiệm",
    projects: "Dấu ấn",
    skills: "Kỹ năng",
    education: "Học vấn",
    contact: "Liên hệ",
    cta: "Tải CV",
  },
  hero: {
    eyebrow: "Open to opportunities",
    name: "Nguyễn Thị Thanh Trà",
    title: "Digital Marketing Specialist",
    location: "Gò Vấp · TP. Hồ Chí Minh",
    intro:
      "Digital Marketing tại GTG CRM (SaaS) — 5+ năm kinh nghiệm xây dựng và vận hành chiến lược Digital Marketing tích hợp cho doanh nghiệp B2B và SME. Chuyên sâu SEO, Performance Marketing, Content Strategy, Brand Marketing và đặc biệt là AI-native workflows: tận dụng Claude, ChatGPT, Gemini, Kling cùng các AI Agent tuỳ chỉnh để tăng tốc đáng kể năng suất marketing.",
    primaryCta: "Tải CV (PDF)",
    secondaryCta: "Xem thành tựu",
    availability: "Mở cho cơ hội phù hợp",
    portrait: "/images/avatar.jpg",
  },
  stats: [
    { value: "+60%", label: "Tăng trưởng organic traffic" },
    { value: "+32%", label: "Tăng tỉ lệ mở email" },
    { value: "20+", label: "Từ khóa đạt Top 3 Google" },
    { value: "200+", label: "Backlink chất lượng đã xây" },
  ],
  about: {
    eyebrow: "Profile",
    headline: "Giới thiệu chuyên môn",
    paragraphs: [
      "Digital Marketing tại GTG CRM — công ty SaaS chuyên về giải pháp CRM cho thị trường Việt Nam, phục vụ 4 phân khúc khách hàng (SME, Enterprise, Freelancer, Doanh nghiệp). Tích luỹ 5+ năm kinh nghiệm thực chiến qua 4 doanh nghiệp ở các mô hình khác nhau: Agency đa ngành, nhập khẩu–phân phối, B2B công nghiệp và SaaS.",
      "Phương pháp tiếp cận của tôi dựa trên dữ liệu và thử nghiệm có hệ thống. Mỗi chiến dịch đều gắn với KPI cụ thể (organic traffic, CTR, CPC, conversion rate, open rate), được tối ưu định kỳ và báo cáo minh bạch với stakeholder. Mục tiêu cuối cùng luôn là tăng trưởng có thể nhân rộng, bền vững và đo lường được.",
      "Chuyên môn cốt lõi bao gồm SEO, Performance Marketing, Content Strategy, Email Marketing Automation, Brand Identity và Marketing Leadership. Đặc biệt chú trọng tích hợp AI (Claude, ChatGPT, Gemini, Kling) vào workflow hàng ngày và xây dựng AI Agent tuỳ chỉnh để tăng năng suất team. Có khả năng thích nghi nhanh với nhiều ngành — từ chu kỳ ra quyết định dài hạn của khách hàng B2B công nghiệp đến mô hình tăng trưởng SaaS theo product-led growth.",
    ],
    cta: "Tải CV PDF",
  },
  experience: {
    eyebrow: "Kinh nghiệm",
    headline: "Hành trình của mình",
    items: [
      {
        role: "Digital Marketing",
        company: "Công ty TNHH GTG CRM",
        period: "06/2025 — Hiện tại",
        location: "TP. Hồ Chí Minh",
        industry: "SaaS · CRM Platform · Multi-segment",
        description:
          "Phụ trách Digital Marketing toàn diện cho sản phẩm SaaS CRM phục vụ 4 phân khúc khách hàng (SME, Enterprise, Freelancer, Doanh nghiệp). Triển khai chiến lược marketing đa kênh, tận dụng AI để tăng tốc workflow, và đo lường mọi quyết định bằng dữ liệu — định hướng growth bền vững và có thể nhân rộng.",
        keyMetrics: [
          { value: "↑ MoM", label: "Signup Growth Rate" },
          { value: "4", label: "Phân khúc khách hàng" },
          { value: "AI-Native", label: "Marketing Workflow" },
        ],
        scope: [
          "Marketing Strategy (Multi-segment)",
          "Product Marketing (SaaS)",
          "Growth & Demand Generation",
          "Content Marketing & Programmatic SEO",
          "Performance Marketing",
          "Marketing Automation",
          "AI Integration & Agent Building",
          "Cross-functional Collaboration",
        ],
        achievements: [
          "Sở hữu Go-to-Market strategy đa phân khúc cho sản phẩm SaaS CRM — định hình ICP, positioning và acquisition channel riêng cho từng nhóm khách hàng (SME, Enterprise, Freelancer, Doanh nghiệp)",
          "Tăng trưởng số lượng signup tháng-trên-tháng (MoM) — KPI cốt lõi đo lường hiệu quả của chiến lược growth",
          "Tích hợp AI sâu vào workflow hàng ngày: Claude/ChatGPT/Gemini cho content production & research, Kling AI cho creative visual, và tự xây dựng AI Agent tuỳ chỉnh để tự động hoá pipeline marketing — tăng năng suất nhiều lần so với cách làm truyền thống",
          "Triển khai marketing funnel SaaS B2B toàn diện: SEO + Content cluster, Paid Ads, Email Automation và Lead Nurturing — mỗi kênh có hệ KPI và dashboard theo dõi riêng",
          "Thử nghiệm và áp dụng các kênh & format mới phù hợp xu hướng 2025+: short-form video, programmatic SEO, generative engine optimization (GEO) cho AI Search, và community-led growth",
          "Phối hợp đa phòng ban (Product, Sales, Customer Success) — đảm bảo marketing message và growth strategy đồng nhất xuyên suốt customer journey",
        ],
        stack: ["HubSpot", "GA4", "GSC", "SEMrush", "Google Ads", "Meta Ads", "Marketing Automation", "Claude", "ChatGPT", "Gemini", "Kling AI", "Perplexity", "Notion"],
        logo: "/images/companies/gtg-crm.png",
      },
      {
        role: "Digital Marketing",
        company: "Công ty TNHH KTTM Thái Khương",
        period: "02/2022 — 06/2025",
        location: "Gò Vấp, HCM",
        industry: "B2B · Thiết bị công nghiệp nhập khẩu",
        description:
          "Phụ trách toàn diện hoạt động Digital Marketing của doanh nghiệp — từ hoạch định chiến lược nội dung, vận hành SEO & Paid Ads, đến quản trị thương hiệu, tổ chức triển lãm và truyền thông nội bộ.",
        keyMetrics: [
          { value: "+40%", label: "Organic Traffic / 6 tháng" },
          { value: "+32%", label: "Email Open Rate" },
          { value: "3", label: "Persona content strategy" },
        ],
        scope: [
          "Brand Marketing & Campaign Planning",
          "Content & SEO",
          "Performance Marketing",
          "Email Marketing Automation",
          "Exhibition & Sự kiện",
          "Truyền thông nội bộ",
        ],
        achievements: [
          "Tăng +40% organic traffic trong 6 tháng nhờ tái cấu trúc content funnel theo persona End-user / Nhà thầu / Đại lý",
          "Quản lý dự án Email Marketing Automation trên nền tảng Getfly — tăng 32% tỉ lệ mở email và cải thiện rõ rệt tỉ lệ phản hồi",
          "Hoạch định và viết kịch bản nội dung dài hạn cho Fanpage, TikTok & Website đồng bộ theo từng nhóm khách hàng mục tiêu",
          "Đại diện công ty phối hợp tổ chức và tham gia các triển lãm chuyên ngành: Vietwater, Propak Vietnam, Waste & Recycling",
          "Cây viết chính của THÔNG TẤN XÃ THÁI KHƯƠNG — kênh truyền thông nội bộ kết nối toàn bộ nhân sự công ty",
          "Quản trị toàn bộ nội dung website WordPress, theo dõi và phân tích dữ liệu người dùng qua GA4 và Google Search Console",
        ],
        stack: ["SEMrush", "GSC", "GA4", "Getfly CRM", "WordPress", "Facebook Ads", "Google Ads", "Canva", "Figma"],
        logo: "/images/companies/thai-khuong.png",
      },
      {
        role: "Performance Marketing Executive",
        company: "Công ty TNHH Erabit Digital Marketing",
        period: "06/2021 — 01/2022",
        location: "TP. Hồ Chí Minh",
        industry: "Marketing Agency · Đa ngành",
        description:
          "Triển khai chiến lược SEO chuyên biệt cho nhiều khách hàng thuộc các ngành khác nhau (Bất động sản, Giáo dục, Dịch vụ). Mỗi dự án được thiết kế content & SEO strategy riêng, bám sát hành vi tìm kiếm đặc thù.",
        keyMetrics: [
          { value: "+40%", label: "Organic Traffic / 6 tháng" },
          { value: "+25%", label: "Engagement tự nhiên" },
          { value: "Multi", label: "Industry portfolio" },
        ],
        scope: [
          "SEO Onpage & Offpage",
          "Social Media Strategy",
          "Website UX/UI Optimization",
          "Reporting & Analysis",
        ],
        achievements: [
          "Đạt mức tăng +40% organic traffic trong 6 tháng cho các dự án thuộc nhiều ngành khác nhau",
          "Triển khai chiến lược SEO toàn diện: nghiên cứu từ khoá, tối ưu Onpage (title, meta, internal link) và Offpage (backlink, guest post, hệ thống vệ tinh)",
          "Phát triển hệ thống backlink chất lượng nhằm nâng cao độ uy tín và sức mạnh tổng thể của website",
          "Quản lý fanpage cho nhiều lĩnh vực — tăng +25% lượng tương tác tự nhiên nhờ nội dung bám sát hành vi và thị hiếu người dùng",
          "Tham gia thiết kế giao diện và tối ưu UX/UI website trên nền tảng WordPress và Eraweb",
          "Thực hiện báo cáo phân tích định kỳ (tuần/tháng/quý) và đề xuất giải pháp cải thiện hiệu suất SEO bền vững",
        ],
        stack: ["Ahrefs", "SEMrush", "Keywordtool.io", "GSC", "GA4", "WordPress", "Eraweb"],
        logo: "/images/companies/erabit.png",
      },
      {
        role: "Digital Marketing Executive",
        company: "Công ty TNHH NK&PP Đông Thái",
        period: "07/2020 — 09/2021",
        location: "TP. Hồ Chí Minh",
        industry: "Nhập khẩu & Phân phối",
        description:
          "Xây dựng và triển khai chiến lược Digital Marketing tổng thể: SEO, Performance Ads, PR báo điện tử và bộ ấn phẩm bán hàng (POSM/Sales Kit). Thiết lập quy chuẩn nhận diện thương hiệu cho doanh nghiệp.",
        keyMetrics: [
          { value: "+60%", label: "Organic Traffic" },
          { value: "20+", label: "Từ khoá Top 3 Google" },
          { value: "-20%", label: "Chi phí CPC" },
        ],
        scope: [
          "SEO Strategy & Execution",
          "Google & Facebook Ads",
          "Online PR & Báo điện tử",
          "POSM / Sales Kit",
          "Brand Identity (CIP)",
        ],
        achievements: [
          "Sản xuất 120+ bài viết chuẩn SEO và xây dựng 200+ backlink chất lượng qua guest post, báo điện tử, hệ thống vệ tinh",
          "Đưa website đạt Top 3 Google cho 20+ từ khoá chính, tăng +60% organic traffic trong vòng 6 tháng",
          "Tối ưu Google Ads & Facebook Ads cho chiến dịch branding và lead-gen: tăng +25% chuyển đổi, giảm -20% CPC sau 3 tháng",
          "Hợp tác báo điện tử triển khai PR chiến dịch lớn — đóng góp đáng kể vào mức độ nhận diện thương hiệu",
          "Quản lý fanpage 2-3 bài/tuần với nội dung bắt trend — tăng +40% lượng tương tác so với giai đoạn trước",
          "Xây dựng và chuẩn hoá Brand Book, Logo Guidelines và quy chuẩn sử dụng thương hiệu trên toàn bộ kênh truyền thông",
          "Triển khai bộ ấn phẩm bán hàng: Wobbler, Catalogue, Leaflet, Brochure, Profile thương hiệu",
        ],
        stack: ["SEMrush", "Ahrefs", "Google Ads", "Facebook Ads", "WordPress", "Báo điện tử PR"],
        logo: "/images/companies/dong-thai.png",
      },
    ],
  },
  projects: {
    eyebrow: "Dấu ấn nổi bật",
    headline: "Một vài kết quả mình tự hào",
    description: "Mỗi mục là một việc cụ thể mình đã trực tiếp triển khai, có số liệu rõ ràng.",
    items: [
      {
        slug: "thai-khuong-content",
        title: "Content Strategy & SEO cho B2B công nghiệp",
        tagline: "Thái Khương — Thiết bị công nghiệp nhập khẩu",
        description:
          "Xây dựng chiến lược nội dung dài hạn theo 3 persona (End-user, Nhà thầu, Đại lý), viết bài SEO kỹ thuật chuyên sâu, quản lý từ khóa với SEMrush.",
        metrics: [
          { label: "Traffic tự nhiên", value: "+40%" },
          { label: "Trong", value: "6 tháng" },
          { label: "Persona", value: "3 nhóm" },
        ],
        tags: ["B2B", "SEO", "Content"],
        cover: "/images/projects/thai-khuong-content.jpg",
      },
      {
        slug: "email-automation-getfly",
        title: "Email Marketing Automation funnel",
        tagline: "Thái Khương — Getfly platform",
        description:
          "Xây dựng phễu nội dung email tự động cho cả khách hàng mới và chăm sóc khách hàng cũ, tối ưu subject line và content theo từng segment.",
        metrics: [
          { label: "Tỉ lệ mở email", value: "+32%" },
          { label: "Phản hồi", value: "Tăng" },
          { label: "Platform", value: "Getfly" },
        ],
        tags: ["Email", "Automation", "B2B"],
        cover: "/images/projects/email-automation-getfly.jpg",
      },
      {
        slug: "dong-thai-seo",
        title: "SEO tổng thể — Top 3 với 20+ keywords",
        tagline: "Đông Thái — Nhập khẩu & Phân phối",
        description:
          "120+ bài SEO + 200+ backlink chất lượng qua guest post và hệ thống vệ tinh. Tối ưu cả onpage và offpage trong 6 tháng.",
        metrics: [
          { label: "Traffic tự nhiên", value: "+60%" },
          { label: "Từ khóa top 3", value: "20+" },
          { label: "Bài SEO", value: "120+" },
        ],
        tags: ["SEO", "Backlink", "Onpage"],
        cover: "/images/projects/dong-thai-seo.jpg",
      },
      {
        slug: "dong-thai-performance",
        title: "Performance Ads — Giảm CPC, tăng chuyển đổi",
        tagline: "Đông Thái — Google & Facebook Ads",
        description:
          "Tối ưu Google & Facebook Ads cho chiến dịch branding và lead-gen trong 3 tháng, kết hợp PR báo điện tử để boost nhận diện.",
        metrics: [
          { label: "Chuyển đổi", value: "+25%" },
          { label: "Chi phí CPC", value: "-20%" },
          { label: "Thời gian", value: "3 tháng" },
        ],
        tags: ["Performance", "Ads", "Lead-gen"],
        cover: "/images/projects/dong-thai-performance.jpg",
      },
    ],
    viewAll: "Xem tất cả",
  },
  skills: {
    eyebrow: "Năng lực chuyên môn",
    headline: "Năng lực cốt lõi",
    description: "Tự đánh giá dựa trên kinh nghiệm thực tế qua 4 doanh nghiệp.",
    items: [
      { name: "Strategy Planning", rating: 9 },
      { name: "AI Workflows & Agent Building", rating: 8.5 },
      { name: "Content Creator", rating: 8.5 },
      { name: "Digital Marketing & SEO", rating: 8 },
      { name: "Project & Campaign Management", rating: 8 },
      { name: "Communication & Collaboration", rating: 8 },
      { name: "Design & Visual Sense", rating: 7 },
    ],
    tools: [
      "Claude",
      "ChatGPT",
      "Gemini",
      "Kling AI",
      "Custom AI Agents",
      "HubSpot",
      "Getfly CRM",
      "SEMrush",
      "Ahrefs",
      "Google Search Console",
      "Google Analytics 4",
      "Keywordtool.io",
      "WordPress",
      "Eraweb",
      "Google Ads",
      "Facebook Ads Manager",
      "Canva",
      "Figma",
    ],
  },
  contact: {
    eyebrow: "Liên hệ",
    headline: "Cảm ơn bạn đã ghé qua",
    description:
      "Nếu thông tin trên phù hợp với vị trí bạn đang tìm, mình rất vui được trò chuyện thêm.",
    cta: "Gửi email",
    downloadCv: "Tải CV PDF",
    email: "nguyenthanhtratm@gmail.com",
    phone: "0849 357 729",
    website: "nguyenthanhtra.info",
    address: "Gò Vấp, TP. Hồ Chí Minh",
  },
  footer: {
    tagline: "Digital Marketing đa kênh — Sài Gòn, từ một cô gái Quảng Bình.",
    sections: [
      {
        title: "Trang",
        links: [
          { label: "Giới thiệu", href: "#about" },
          { label: "Kinh nghiệm", href: "#experience" },
          { label: "Dấu ấn", href: "#projects" },
          { label: "Kỹ năng", href: "#skills" },
          { label: "Học vấn", href: "#education" },
          { label: "Liên hệ", href: "#contact" },
        ],
      },
      {
        title: "Liên hệ",
        links: [
          { label: "nguyenthanhtratm@gmail.com", href: "mailto:nguyenthanhtratm@gmail.com" },
          { label: "0849 357 729", href: "tel:+84849357729" },
          { label: "nguyenthanhtra.info", href: "https://nguyenthanhtra.info" },
        ],
      },
    ],
    social: [
      { label: "Email", href: "mailto:nguyenthanhtratm@gmail.com", icon: "mail" },
      { label: "Phone", href: "tel:+84849357729", icon: "phone" },
      { label: "Website", href: "https://nguyenthanhtra.info", icon: "globe" },
    ],
    copyright: "© 2026 Nguyễn Thị Thanh Trà.",
  },
  education: {
    eyebrow: "Học vấn",
    headline: "Nền tảng",
    items: [
      {
        school: "Trường Đại học Công nghiệp TP.HCM (IUH)",
        degree: "Cử nhân Thương mại Điện tử",
        period: "Tốt nghiệp 2022",
        detail: "GPA: 3.0/4.0",
      },
    ],
  },
};
